---
# Deploy a VM from a ISO using Ansible 'vmware_guest' module
- name: Deploy VM from iso
  vmware_guest:
    hostname: '{{ deploy_vCenter_host }}'
    username: '{{ deploy_vCenter_user }}'
    password: '{{ deploy_vCenter_password }}'
    validate_certs: no
    datacenter: '{{ deploy_vCenter_datacenter }}'
    esxi_hostname: "{{ deploy_vCenter_esxhost }}"
    #cluster: '{{ deploy_vsphere_cluster }}'
    #resource_pool: '{{ deploy_vsphere_resourcepool }}'
    folder: '{{ deploy_vCenter_folder }}'
    name: '{{ inventory_hostname }}'
    #state: poweredon
    #template: OS_Ubuntu_14_template
    annotation: "{{ guest_notes }}"
    guest_id: ubuntu64guest
    disk:
    - size_gb: "{{ guest_disk_size | default(80) }}"
      type: thin
      datastore: '{{ deploy_vCenter_datastore }}'
    networks:
    - name: VM Network
      device_type: vmxnet3
      start_connected: True
    hardware:
      memory_mb: "{{ vm_memory | default(8192) }}"
      num_cpus: "{{ vm_cpu | default(8) }}"
    cdrom:
      controller_number: 0
      unit_number: 0
      type: "iso"
      iso_path: "[datastore18_2] testisomaster/motadata-master-1604-7.6.400.cf44558-new.iso"
    wait_for_ip_address: True
    state: present
  register: newvm 
 
- name: IP address of Virtual Machine 
  debug:
    msg: "ip address of VM is : {{ newvm.instance.ipv4 }} "
